// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: game.proto

package k8s_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameService_CreateGame_FullMethodName            = "/GameService/CreateGame"
	GameService_GetGame_FullMethodName               = "/GameService/GetGame"
	GameService_SubscribeToGameStatus_FullMethodName = "/GameService/SubscribeToGameStatus"
	GameService_GetPlayerLogs_FullMethodName         = "/GameService/GetPlayerLogs"
	GameService_GetGameLogs_FullMethodName           = "/GameService/GetGameLogs"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error)
	GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error)
	SubscribeToGameStatus(ctx context.Context, in *GameStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameStatusResponse], error)
	GetPlayerLogs(ctx context.Context, in *PlayerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerLog], error)
	GetGameLogs(ctx context.Context, in *GameLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameLog], error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) CreateGame(ctx context.Context, in *CreateGameRequest, opts ...grpc.CallOption) (*CreateGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameResponse)
	err := c.cc.Invoke(ctx, GameService_CreateGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetGame(ctx context.Context, in *GetGameRequest, opts ...grpc.CallOption) (*GetGameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGameResponse)
	err := c.cc.Invoke(ctx, GameService_GetGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SubscribeToGameStatus(ctx context.Context, in *GameStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[0], GameService_SubscribeToGameStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GameStatusRequest, GameStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_SubscribeToGameStatusClient = grpc.ServerStreamingClient[GameStatusResponse]

func (c *gameServiceClient) GetPlayerLogs(ctx context.Context, in *PlayerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[1], GameService_GetPlayerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PlayerLogsRequest, PlayerLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_GetPlayerLogsClient = grpc.ServerStreamingClient[PlayerLog]

func (c *gameServiceClient) GetGameLogs(ctx context.Context, in *GameLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GameLog], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[2], GameService_GetGameLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GameLogsRequest, GameLog]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_GetGameLogsClient = grpc.ServerStreamingClient[GameLog]

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility.
type GameServiceServer interface {
	CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error)
	GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error)
	SubscribeToGameStatus(*GameStatusRequest, grpc.ServerStreamingServer[GameStatusResponse]) error
	GetPlayerLogs(*PlayerLogsRequest, grpc.ServerStreamingServer[PlayerLog]) error
	GetGameLogs(*GameLogsRequest, grpc.ServerStreamingServer[GameLog]) error
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameServiceServer struct{}

func (UnimplementedGameServiceServer) CreateGame(context.Context, *CreateGameRequest) (*CreateGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGame not implemented")
}
func (UnimplementedGameServiceServer) GetGame(context.Context, *GetGameRequest) (*GetGameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGame not implemented")
}
func (UnimplementedGameServiceServer) SubscribeToGameStatus(*GameStatusRequest, grpc.ServerStreamingServer[GameStatusResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToGameStatus not implemented")
}
func (UnimplementedGameServiceServer) GetPlayerLogs(*PlayerLogsRequest, grpc.ServerStreamingServer[PlayerLog]) error {
	return status.Errorf(codes.Unimplemented, "method GetPlayerLogs not implemented")
}
func (UnimplementedGameServiceServer) GetGameLogs(*GameLogsRequest, grpc.ServerStreamingServer[GameLog]) error {
	return status.Errorf(codes.Unimplemented, "method GetGameLogs not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}
func (UnimplementedGameServiceServer) testEmbeddedByValue()                     {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_CreateGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).CreateGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_CreateGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).CreateGame(ctx, req.(*CreateGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameService_GetGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetGame(ctx, req.(*GetGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SubscribeToGameStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GameStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServiceServer).SubscribeToGameStatus(m, &grpc.GenericServerStream[GameStatusRequest, GameStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_SubscribeToGameStatusServer = grpc.ServerStreamingServer[GameStatusResponse]

func _GameService_GetPlayerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayerLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServiceServer).GetPlayerLogs(m, &grpc.GenericServerStream[PlayerLogsRequest, PlayerLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_GetPlayerLogsServer = grpc.ServerStreamingServer[PlayerLog]

func _GameService_GetGameLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GameLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServiceServer).GetGameLogs(m, &grpc.GenericServerStream[GameLogsRequest, GameLog]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameService_GetGameLogsServer = grpc.ServerStreamingServer[GameLog]

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGame",
			Handler:    _GameService_CreateGame_Handler,
		},
		{
			MethodName: "GetGame",
			Handler:    _GameService_GetGame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToGameStatus",
			Handler:       _GameService_SubscribeToGameStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPlayerLogs",
			Handler:       _GameService_GetPlayerLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetGameLogs",
			Handler:       _GameService_GetGameLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game.proto",
}
